### ISSUE TITLE
Ch8_Quiz #3 Says I am both correct and incorrect

### ISSUE THREAD

**Issue by ZebGirouard** [sarahholden/fundamentals#104]
When I answer "False" I see a "That's Correct! ..." dialog, but if I keep scrolling, I also see a "Not Quite...." dialog.  Pretty sure that shouldn't happen.

**Comment by ZebGirouard** [comment]
This also happens with number 7.

When I get through question 7, it opens up a bunch of other questions I didn't see before and changes my progress (this happened a lot in the old fundamentals, too).

When I get through question 7, some answers are also correct and incorrect, before I even answered them.

**Comment by ZebGirouard** [comment]
At question 10, it opens up question 11 that I couldn't see before.

**Comment by ZebGirouard** [comment]
And 11 is also correct and incorrect when I answer it.

Final result: 3/10 despite me getting them all right.  Again, if I were a student I would want to throw things right now.

**Comment by amyealmeida** [comment]
@ZebGirouard there were problems with the logic jumps which made it so both "Correct" and "Not Quite" were showing up before the student answers a question.  This should be fixed now, with the exception of one question that is giving me trouble.  Working on it!

As for the final calculation of students score, we are going to change all questions to multiple choice so that this doesn't happen any more.

Thanks so much!
