### ISSUE TITLE
Ch9_Quiz Issues

### ISSUE THREAD

**Issue by ZebGirouard** [sarahholden/fundamentals#134]
@amyealmeida , a new treat for you!

Not Quite and Correct are both showing up on question 3, 4, 5, and 7.

Also seems like I can't really scroll the Quiz.  Refreshing the page seems to fix it, not sure how I got into this state, but figured I'd let you know.

After I answer question 5, a bunch of other questions show up.

I got question 6 wrong, even though I wrote "It's light outside!" , which is literally what they say the answer is, character-for-character.

The non-scrolling becomes a big issue at the bottom, because when I answer 7 it actually bounces me up to the question so I cannot physically complete this quiz.

**Comment by ZebGirouard** [comment]
Also tells me I got 0/10 right after refreshing and taking it again.  Confusing to say the least.

**Comment by amyealmeida** [comment]
Thanks, @ZebGirouard 

I cannot figure out why Typeform is doing this (showing Not Quite and Correct) for some questions, because they all have the exact same logic rules behind them.  I'm working on it!  Also unclear why the scrolling stops.  **Ugh** 

As for Question 6, that will be resolved because we are going to make all the questions multiple choice!

**Comment by amyealmeida** [comment]
logic has been reconfigured!
