### ISSUE TITLE
Don't tell them that ; isn't required if you're requiring it

### ISSUE THREAD

**Issue by payne-chris-r** [sarahholden/fundamentals#157]
Don't tell them that ; isn't required if you're "requiring" it. It can be a useful fiction.

**Comment by sarahholden** [comment]
Hey @payne-chris-r Thanks! Would you be able to include the lesson number in the issue title so I can know where to look for all issues? Appreciate it.

**Comment by sarahholden** [comment]
e.g.  **7.1 Data Types - Missing Semicolon**

**Comment by payne-chris-r** [comment]
Yeah @sarahholden I tried, but forgot in some places! Did you find this one?

**Comment by sarahholden** [comment]
It's tricky since it's such a broad search term so without a lesson number it could be anywhere. Is this the portion you're referring to:

>   After each line of instruction, be sure to use a semicolon. Although you may be able to get away without using semicolons in some browsers, JavaScript often does nasty things when it guesses where to put semicolons itself. It's better to be explicit and tell the interpreter exactly where a statement should end.

I think that is helpful information since students sometimes think, "Hey, not adding a semicolon isn't giving me an error" but if they ever compress their code things would take a nasty turn. But I still think it doesn't say that they are optional.
