### ISSUE TITLE
9 (all of it) - inconsistent use of semicolons following functions

### ISSUE THREAD

**Issue by susiremondi** [sarahholden/fundamentals#171]
Sometimes you have semicolons after function definitions and sometimes you don't - even on the same page. And sometimes you have semicolons after function declarations and not function expressions, or vice versa....

Example - in 9.1, all of the text has semicolons, but none of the screenshots do.

Example 2, in the _9.5 cheat sheet_, under '_defining and calling javascript functions'_, no semicolon. The next section, under parameters, there is a semicolon after an identically declared function. 

tbh, I'm not sure whether there should or should not be semicolons after function declaration or function expressions (well, I think I do but would rather someone that currently codes in JS call it), but please find out and fix them so it's consistent.

**Comment by sarahholden** [comment]
Hi @susiremondi These should all be fixed _except_ for in the graphics, which can't be fixed at this time, unfortunately. I think since it's a small thing the benefit of having those images outweighs the missing semicolons, although in the future it would be nice to make sure the graphics have semicolons after function expressions.

And it is a little confusing since it's not valid to have semicolons after function declarations but they should always go after function expressions. I think we want to encourage students to use function expressions for Fundamentals and only briefly mention function declarations, so I've updated any function declarations I saw to function expressions and added semicolons.

Thanks!

**Comment by susiremondi** [comment]
Cool, that's what I thought, but I didn't want to suggest in case there was
some JS update i didn't know about. Yeah, as long as all the text and
instructions are explicitly correct, I agree the screenshots are a lower
priority. It'd just be incredibly confusing for the students if we were
inconsistent with what we do ourselves, since we're teaching them what to
do. Thanks!
