### ISSUE TITLE
10.6 - deliverable screenshot possibly should be cropped so the popup isn't there

### ISSUE THREAD

**Issue by susiremondi** [sarahholden/fundamentals#180]
Because that part isn't relevant (also, does it even happen? I'm not following along with the exercises, so maybe.... but it's still not relevant)

**What it looks like:**
![image](https://cloud.githubusercontent.com/assets/25623009/22843960/e3b89a06-efa9-11e6-9899-2ed9ff1a01cf.png)

**What it probably should look like:**
![image](https://cloud.githubusercontent.com/assets/25623009/22843967/e78ecfec-efa9-11e6-9894-27bf911b1795.png)

**Comment by sarahholden** [comment]
Hey @susiremondi The alert is relevant since the students are creating the alert in the assignment. I can make this into two screenshots, I do realize some students will have their inspector on the side, but I thought it would be helpful to have one screenshot with everything that's supposed to happen for the assignment.

**Comment by sarahholden** [comment]
i.e. even though the students aren't creating the alert in this assignment, if everything is still hooked up correctly it should still pop up, otherwise there might be an error with their code.

**Comment by sarahholden** [comment]
Cropped along with the previous crops
