### ISSUE TITLE
General: Syntax Errors in JSBin

### ISSUE THREAD

**Issue by ZebGirouard** [sarahholden/fundamentals#90]
The chance of a student getting a syntax error in JSBin is quite high.  Unfortunately, the error messages are super unhelpful like:

"Syntax error at " (like doesn't even give a helpful character or line number)

I have no idea how to resolve this, and to make matters worse, it seems that sometimes you can get into an unrecoverable state with these errors, and the only way out is to refresh the page.

**Comment by sarahholden** [comment]
@ZebGirouard Hmm...unfortunately I don't know if there is a quick fix for this one right now. The underlying issue is that JS Bin isn't a super reliable or easy place to work. But this should be fixed when we migrate Fundamentals to the new platform. 

For now, do you think adding in some debugging instructions would help?

**Comment by ZebGirouard** [comment]
@sarahholden , I think any note we add will just be confusing.  How do we communicate

"If you at one point had a syntax error, but fixed it later, sometimes you need to refresh the page in order to make the syntax error go away."

Especially when they probably don't know what a syntax error really is.

I think we just have to call it a lost cause, and hope for a better platform in the future.

**Comment by sarahholden** [comment]
We're working on it! Fundamentals 4.0 will be hosted on a new platform. Hopefully much better!

Closing out for now.
